### ISSUE TITLE
create boat registration, include validations

### ISSUE THREAD

**Issue by BMcSpillin** [ricardolopezg/nycda_workshop_shipped_validations#3]
(hidden: profile_id), boat name, capacity (in units of containers), location docked

**Comment by ricardolopezg** [comment]
*****_REQUIREMENT ***_**\* must have a unique name

**Comment by ricardolopezg** [comment]
UNIQUE NAME DONE

LOCATIONS Selected from hard coding left

**Comment by ricardolopezg** [comment]
locations done
